// Code generated by MockGen. DO NOT EDIT.
// Source: audio_decoder.go
//
// Generated by this command:
//
//	mockgen -source=audio_decoder.go -destination=../mocks/mock_audio_decoder.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomedia "github.com/ugparu/gomedia"
	buffer "github.com/ugparu/gomedia/utils/buffer"
	gomock "go.uber.org/mock/gomock"
)

// MockInnerAudioDecoder is a mock of InnerAudioDecoder interface.
type MockInnerAudioDecoder struct {
	ctrl     *gomock.Controller
	recorder *MockInnerAudioDecoderMockRecorder
	isgomock struct{}
}

// MockInnerAudioDecoderMockRecorder is the mock recorder for MockInnerAudioDecoder.
type MockInnerAudioDecoderMockRecorder struct {
	mock *MockInnerAudioDecoder
}

// NewMockInnerAudioDecoder creates a new mock instance.
func NewMockInnerAudioDecoder(ctrl *gomock.Controller) *MockInnerAudioDecoder {
	mock := &MockInnerAudioDecoder{ctrl: ctrl}
	mock.recorder = &MockInnerAudioDecoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInnerAudioDecoder) EXPECT() *MockInnerAudioDecoderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockInnerAudioDecoder) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockInnerAudioDecoderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockInnerAudioDecoder)(nil).Close))
}

// Decode mocks base method.
func (m *MockInnerAudioDecoder) Decode(inData []byte, ring *buffer.GrowingRingAlloc) ([]byte, *buffer.SlotHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", inData, ring)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(*buffer.SlotHandle)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Decode indicates an expected call of Decode.
func (mr *MockInnerAudioDecoderMockRecorder) Decode(inData, ring any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockInnerAudioDecoder)(nil).Decode), inData, ring)
}

// Init mocks base method.
func (m *MockInnerAudioDecoder) Init(params gomedia.AudioCodecParameters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockInnerAudioDecoderMockRecorder) Init(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockInnerAudioDecoder)(nil).Init), params)
}
