// Code generated by MockGen. DO NOT EDIT.
// Source: utils.go
//
// Generated by this command:
//
//	mockgen -source=utils.go -destination=../../mocks/mock_lifecycle.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	lifecycle "github.com/ugparu/gomedia/utils/lifecycle"
	gomock "go.uber.org/mock/gomock"
)

// MockInstance is a mock of Instance interface.
type MockInstance struct {
	ctrl     *gomock.Controller
	recorder *MockInstanceMockRecorder
	isgomock struct{}
}

// MockInstanceMockRecorder is the mock recorder for MockInstance.
type MockInstanceMockRecorder struct {
	mock *MockInstance
}

// NewMockInstance creates a new mock instance.
func NewMockInstance(ctrl *gomock.Controller) *MockInstance {
	mock := &MockInstance{ctrl: ctrl}
	mock.recorder = &MockInstanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstance) EXPECT() *MockInstanceMockRecorder {
	return m.recorder
}

// Release mocks base method.
func (m *MockInstance) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockInstanceMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockInstance)(nil).Release))
}

// String mocks base method.
func (m *MockInstance) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockInstanceMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockInstance)(nil).String))
}

// MockAsyncInstance is a mock of AsyncInstance interface.
type MockAsyncInstance struct {
	ctrl     *gomock.Controller
	recorder *MockAsyncInstanceMockRecorder
	isgomock struct{}
}

// MockAsyncInstanceMockRecorder is the mock recorder for MockAsyncInstance.
type MockAsyncInstanceMockRecorder struct {
	mock *MockAsyncInstance
}

// NewMockAsyncInstance creates a new mock instance.
func NewMockAsyncInstance(ctrl *gomock.Controller) *MockAsyncInstance {
	mock := &MockAsyncInstance{ctrl: ctrl}
	mock.recorder = &MockAsyncInstanceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAsyncInstance) EXPECT() *MockAsyncInstanceMockRecorder {
	return m.recorder
}

// Release mocks base method.
func (m *MockAsyncInstance) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockAsyncInstanceMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockAsyncInstance)(nil).Release))
}

// Step mocks base method.
func (m *MockAsyncInstance) Step(stopChan <-chan struct{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Step", stopChan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Step indicates an expected call of Step.
func (mr *MockAsyncInstanceMockRecorder) Step(stopChan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Step", reflect.TypeOf((*MockAsyncInstance)(nil).Step), stopChan)
}

// String mocks base method.
func (m *MockAsyncInstance) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockAsyncInstanceMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockAsyncInstance)(nil).String))
}

// MockManager is a mock of Manager interface.
type MockManager[T lifecycle.Instance] struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder[T]
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder[T lifecycle.Instance] struct {
	mock *MockManager[T]
}

// NewMockManager creates a new mock instance.
func NewMockManager[T lifecycle.Instance](ctrl *gomock.Controller) *MockManager[T] {
	mock := &MockManager[T]{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager[T]) EXPECT() *MockManagerMockRecorder[T] {
	return m.recorder
}

// Close mocks base method.
func (m *MockManager[T]) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockManagerMockRecorder[T]) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockManager[T])(nil).Close))
}

// Start mocks base method.
func (m *MockManager[T]) Start(arg0 func(T) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockManagerMockRecorder[T]) Start(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockManager[T])(nil).Start), arg0)
}

// MockAsyncManager is a mock of AsyncManager interface.
type MockAsyncManager[T lifecycle.AsyncInstance] struct {
	ctrl     *gomock.Controller
	recorder *MockAsyncManagerMockRecorder[T]
	isgomock struct{}
}

// MockAsyncManagerMockRecorder is the mock recorder for MockAsyncManager.
type MockAsyncManagerMockRecorder[T lifecycle.AsyncInstance] struct {
	mock *MockAsyncManager[T]
}

// NewMockAsyncManager creates a new mock instance.
func NewMockAsyncManager[T lifecycle.AsyncInstance](ctrl *gomock.Controller) *MockAsyncManager[T] {
	mock := &MockAsyncManager[T]{ctrl: ctrl}
	mock.recorder = &MockAsyncManagerMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAsyncManager[T]) EXPECT() *MockAsyncManagerMockRecorder[T] {
	return m.recorder
}

// Close mocks base method.
func (m *MockAsyncManager[T]) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockAsyncManagerMockRecorder[T]) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAsyncManager[T])(nil).Close))
}

// Done mocks base method.
func (m *MockAsyncManager[T]) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockAsyncManagerMockRecorder[T]) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockAsyncManager[T])(nil).Done))
}

// Start mocks base method.
func (m *MockAsyncManager[T]) Start(arg0 func(T) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockAsyncManagerMockRecorder[T]) Start(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockAsyncManager[T])(nil).Start), arg0)
}
