// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=../../mocks/mock_buffer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPooledBuffer is a mock of PooledBuffer interface.
type MockPooledBuffer struct {
	ctrl     *gomock.Controller
	recorder *MockPooledBufferMockRecorder
	isgomock struct{}
}

// MockPooledBufferMockRecorder is the mock recorder for MockPooledBuffer.
type MockPooledBufferMockRecorder struct {
	mock *MockPooledBuffer
}

// NewMockPooledBuffer creates a new mock instance.
func NewMockPooledBuffer(ctrl *gomock.Controller) *MockPooledBuffer {
	mock := &MockPooledBuffer{ctrl: ctrl}
	mock.recorder = &MockPooledBufferMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPooledBuffer) EXPECT() *MockPooledBufferMockRecorder {
	return m.recorder
}

// Cap mocks base method.
func (m *MockPooledBuffer) Cap() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cap")
	ret0, _ := ret[0].(int)
	return ret0
}

// Cap indicates an expected call of Cap.
func (mr *MockPooledBufferMockRecorder) Cap() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cap", reflect.TypeOf((*MockPooledBuffer)(nil).Cap))
}

// Data mocks base method.
func (m *MockPooledBuffer) Data() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Data")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Data indicates an expected call of Data.
func (mr *MockPooledBufferMockRecorder) Data() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Data", reflect.TypeOf((*MockPooledBuffer)(nil).Data))
}

// Len mocks base method.
func (m *MockPooledBuffer) Len() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int)
	return ret0
}

// Len indicates an expected call of Len.
func (mr *MockPooledBufferMockRecorder) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockPooledBuffer)(nil).Len))
}

// Release mocks base method.
func (m *MockPooledBuffer) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockPooledBufferMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockPooledBuffer)(nil).Release))
}

// Resize mocks base method.
func (m *MockPooledBuffer) Resize(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Resize", arg0)
}

// Resize indicates an expected call of Resize.
func (mr *MockPooledBufferMockRecorder) Resize(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resize", reflect.TypeOf((*MockPooledBuffer)(nil).Resize), arg0)
}
