// Code generated by MockGen. DO NOT EDIT.
// Source: muxer.go
//
// Generated by this command:
//
//	mockgen -source=muxer.go -destination=../../mocks/mock_rtsp_muxer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomedia "github.com/ugparu/gomedia"
	gomock "go.uber.org/mock/gomock"
)

// MockrtpVideoMuxer is a mock of rtpVideoMuxer interface.
type MockrtpVideoMuxer struct {
	ctrl     *gomock.Controller
	recorder *MockrtpVideoMuxerMockRecorder
	isgomock struct{}
}

// MockrtpVideoMuxerMockRecorder is the mock recorder for MockrtpVideoMuxer.
type MockrtpVideoMuxerMockRecorder struct {
	mock *MockrtpVideoMuxer
}

// NewMockrtpVideoMuxer creates a new mock instance.
func NewMockrtpVideoMuxer(ctrl *gomock.Controller) *MockrtpVideoMuxer {
	mock := &MockrtpVideoMuxer{ctrl: ctrl}
	mock.recorder = &MockrtpVideoMuxerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrtpVideoMuxer) EXPECT() *MockrtpVideoMuxerMockRecorder {
	return m.recorder
}

// WritePacket mocks base method.
func (m *MockrtpVideoMuxer) WritePacket(arg0 gomedia.VideoPacket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WritePacket", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// WritePacket indicates an expected call of WritePacket.
func (mr *MockrtpVideoMuxerMockRecorder) WritePacket(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WritePacket", reflect.TypeOf((*MockrtpVideoMuxer)(nil).WritePacket), arg0)
}
