// Code generated by MockGen. DO NOT EDIT.
// Source: video_decoder.go
//
// Generated by this command:
//
//	mockgen -source=video_decoder.go -destination=../mocks/mock_video_decoder.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	image "image"
	reflect "reflect"

	gomedia "github.com/ugparu/gomedia"
	gomock "go.uber.org/mock/gomock"
)

// MockInnerVideoDecoder is a mock of InnerVideoDecoder interface.
type MockInnerVideoDecoder struct {
	ctrl     *gomock.Controller
	recorder *MockInnerVideoDecoderMockRecorder
	isgomock struct{}
}

// MockInnerVideoDecoderMockRecorder is the mock recorder for MockInnerVideoDecoder.
type MockInnerVideoDecoderMockRecorder struct {
	mock *MockInnerVideoDecoder
}

// NewMockInnerVideoDecoder creates a new mock instance.
func NewMockInnerVideoDecoder(ctrl *gomock.Controller) *MockInnerVideoDecoder {
	mock := &MockInnerVideoDecoder{ctrl: ctrl}
	mock.recorder = &MockInnerVideoDecoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInnerVideoDecoder) EXPECT() *MockInnerVideoDecoderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockInnerVideoDecoder) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockInnerVideoDecoderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockInnerVideoDecoder)(nil).Close))
}

// Decode mocks base method.
func (m *MockInnerVideoDecoder) Decode(pkt gomedia.VideoPacket) (image.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", pkt)
	ret0, _ := ret[0].(image.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decode indicates an expected call of Decode.
func (mr *MockInnerVideoDecoderMockRecorder) Decode(pkt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockInnerVideoDecoder)(nil).Decode), pkt)
}

// Feed mocks base method.
func (m *MockInnerVideoDecoder) Feed(pkt gomedia.VideoPacket) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Feed", pkt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Feed indicates an expected call of Feed.
func (mr *MockInnerVideoDecoderMockRecorder) Feed(pkt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Feed", reflect.TypeOf((*MockInnerVideoDecoder)(nil).Feed), pkt)
}

// Init mocks base method.
func (m *MockInnerVideoDecoder) Init(codecPar gomedia.VideoCodecParameters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", codecPar)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockInnerVideoDecoderMockRecorder) Init(codecPar any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockInnerVideoDecoder)(nil).Init), codecPar)
}
