// Code generated by MockGen. DO NOT EDIT.
// Source: gomedia.go
//
// Generated by this command:
//
//	mockgen -source=gomedia.go -destination=mocks/mock_gomedia.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomedia "github.com/ugparu/gomedia"
	rgb "github.com/ugparu/gomedia/frame/rgb"
	gomock "go.uber.org/mock/gomock"
)

// MockCodecParameters is a mock of CodecParameters interface.
type MockCodecParameters struct {
	ctrl     *gomock.Controller
	recorder *MockCodecParametersMockRecorder
	isgomock struct{}
}

// MockCodecParametersMockRecorder is the mock recorder for MockCodecParameters.
type MockCodecParametersMockRecorder struct {
	mock *MockCodecParameters
}

// NewMockCodecParameters creates a new mock instance.
func NewMockCodecParameters(ctrl *gomock.Controller) *MockCodecParameters {
	mock := &MockCodecParameters{ctrl: ctrl}
	mock.recorder = &MockCodecParametersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodecParameters) EXPECT() *MockCodecParametersMockRecorder {
	return m.recorder
}

// Bitrate mocks base method.
func (m *MockCodecParameters) Bitrate() uint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bitrate")
	ret0, _ := ret[0].(uint)
	return ret0
}

// Bitrate indicates an expected call of Bitrate.
func (mr *MockCodecParametersMockRecorder) Bitrate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bitrate", reflect.TypeOf((*MockCodecParameters)(nil).Bitrate))
}

// SetBitrate mocks base method.
func (m *MockCodecParameters) SetBitrate(arg0 uint) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBitrate", arg0)
}

// SetBitrate indicates an expected call of SetBitrate.
func (mr *MockCodecParametersMockRecorder) SetBitrate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBitrate", reflect.TypeOf((*MockCodecParameters)(nil).SetBitrate), arg0)
}

// SetStreamIndex mocks base method.
func (m *MockCodecParameters) SetStreamIndex(arg0 uint8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStreamIndex", arg0)
}

// SetStreamIndex indicates an expected call of SetStreamIndex.
func (mr *MockCodecParametersMockRecorder) SetStreamIndex(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStreamIndex", reflect.TypeOf((*MockCodecParameters)(nil).SetStreamIndex), arg0)
}

// StreamIndex mocks base method.
func (m *MockCodecParameters) StreamIndex() uint8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamIndex")
	ret0, _ := ret[0].(uint8)
	return ret0
}

// StreamIndex indicates an expected call of StreamIndex.
func (mr *MockCodecParametersMockRecorder) StreamIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamIndex", reflect.TypeOf((*MockCodecParameters)(nil).StreamIndex))
}

// Tag mocks base method.
func (m *MockCodecParameters) Tag() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tag")
	ret0, _ := ret[0].(string)
	return ret0
}

// Tag indicates an expected call of Tag.
func (mr *MockCodecParametersMockRecorder) Tag() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tag", reflect.TypeOf((*MockCodecParameters)(nil).Tag))
}

// Type mocks base method.
func (m *MockCodecParameters) Type() gomedia.CodecType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(gomedia.CodecType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockCodecParametersMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockCodecParameters)(nil).Type))
}

// MockVideoCodecParameters is a mock of VideoCodecParameters interface.
type MockVideoCodecParameters struct {
	ctrl     *gomock.Controller
	recorder *MockVideoCodecParametersMockRecorder
	isgomock struct{}
}

// MockVideoCodecParametersMockRecorder is the mock recorder for MockVideoCodecParameters.
type MockVideoCodecParametersMockRecorder struct {
	mock *MockVideoCodecParameters
}

// NewMockVideoCodecParameters creates a new mock instance.
func NewMockVideoCodecParameters(ctrl *gomock.Controller) *MockVideoCodecParameters {
	mock := &MockVideoCodecParameters{ctrl: ctrl}
	mock.recorder = &MockVideoCodecParametersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoCodecParameters) EXPECT() *MockVideoCodecParametersMockRecorder {
	return m.recorder
}

// Bitrate mocks base method.
func (m *MockVideoCodecParameters) Bitrate() uint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bitrate")
	ret0, _ := ret[0].(uint)
	return ret0
}

// Bitrate indicates an expected call of Bitrate.
func (mr *MockVideoCodecParametersMockRecorder) Bitrate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bitrate", reflect.TypeOf((*MockVideoCodecParameters)(nil).Bitrate))
}

// FPS mocks base method.
func (m *MockVideoCodecParameters) FPS() uint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FPS")
	ret0, _ := ret[0].(uint)
	return ret0
}

// FPS indicates an expected call of FPS.
func (mr *MockVideoCodecParametersMockRecorder) FPS() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FPS", reflect.TypeOf((*MockVideoCodecParameters)(nil).FPS))
}

// Height mocks base method.
func (m *MockVideoCodecParameters) Height() uint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Height")
	ret0, _ := ret[0].(uint)
	return ret0
}

// Height indicates an expected call of Height.
func (mr *MockVideoCodecParametersMockRecorder) Height() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Height", reflect.TypeOf((*MockVideoCodecParameters)(nil).Height))
}

// SetBitrate mocks base method.
func (m *MockVideoCodecParameters) SetBitrate(arg0 uint) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBitrate", arg0)
}

// SetBitrate indicates an expected call of SetBitrate.
func (mr *MockVideoCodecParametersMockRecorder) SetBitrate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBitrate", reflect.TypeOf((*MockVideoCodecParameters)(nil).SetBitrate), arg0)
}

// SetStreamIndex mocks base method.
func (m *MockVideoCodecParameters) SetStreamIndex(arg0 uint8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStreamIndex", arg0)
}

// SetStreamIndex indicates an expected call of SetStreamIndex.
func (mr *MockVideoCodecParametersMockRecorder) SetStreamIndex(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStreamIndex", reflect.TypeOf((*MockVideoCodecParameters)(nil).SetStreamIndex), arg0)
}

// StreamIndex mocks base method.
func (m *MockVideoCodecParameters) StreamIndex() uint8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamIndex")
	ret0, _ := ret[0].(uint8)
	return ret0
}

// StreamIndex indicates an expected call of StreamIndex.
func (mr *MockVideoCodecParametersMockRecorder) StreamIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamIndex", reflect.TypeOf((*MockVideoCodecParameters)(nil).StreamIndex))
}

// Tag mocks base method.
func (m *MockVideoCodecParameters) Tag() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tag")
	ret0, _ := ret[0].(string)
	return ret0
}

// Tag indicates an expected call of Tag.
func (mr *MockVideoCodecParametersMockRecorder) Tag() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tag", reflect.TypeOf((*MockVideoCodecParameters)(nil).Tag))
}

// Type mocks base method.
func (m *MockVideoCodecParameters) Type() gomedia.CodecType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(gomedia.CodecType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockVideoCodecParametersMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockVideoCodecParameters)(nil).Type))
}

// Width mocks base method.
func (m *MockVideoCodecParameters) Width() uint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Width")
	ret0, _ := ret[0].(uint)
	return ret0
}

// Width indicates an expected call of Width.
func (mr *MockVideoCodecParametersMockRecorder) Width() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Width", reflect.TypeOf((*MockVideoCodecParameters)(nil).Width))
}

// MockAudioCodecParameters is a mock of AudioCodecParameters interface.
type MockAudioCodecParameters struct {
	ctrl     *gomock.Controller
	recorder *MockAudioCodecParametersMockRecorder
	isgomock struct{}
}

// MockAudioCodecParametersMockRecorder is the mock recorder for MockAudioCodecParameters.
type MockAudioCodecParametersMockRecorder struct {
	mock *MockAudioCodecParameters
}

// NewMockAudioCodecParameters creates a new mock instance.
func NewMockAudioCodecParameters(ctrl *gomock.Controller) *MockAudioCodecParameters {
	mock := &MockAudioCodecParameters{ctrl: ctrl}
	mock.recorder = &MockAudioCodecParametersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAudioCodecParameters) EXPECT() *MockAudioCodecParametersMockRecorder {
	return m.recorder
}

// Bitrate mocks base method.
func (m *MockAudioCodecParameters) Bitrate() uint {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bitrate")
	ret0, _ := ret[0].(uint)
	return ret0
}

// Bitrate indicates an expected call of Bitrate.
func (mr *MockAudioCodecParametersMockRecorder) Bitrate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bitrate", reflect.TypeOf((*MockAudioCodecParameters)(nil).Bitrate))
}

// Channels mocks base method.
func (m *MockAudioCodecParameters) Channels() uint8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Channels")
	ret0, _ := ret[0].(uint8)
	return ret0
}

// Channels indicates an expected call of Channels.
func (mr *MockAudioCodecParametersMockRecorder) Channels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Channels", reflect.TypeOf((*MockAudioCodecParameters)(nil).Channels))
}

// SampleFormat mocks base method.
func (m *MockAudioCodecParameters) SampleFormat() gomedia.SampleFormat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SampleFormat")
	ret0, _ := ret[0].(gomedia.SampleFormat)
	return ret0
}

// SampleFormat indicates an expected call of SampleFormat.
func (mr *MockAudioCodecParametersMockRecorder) SampleFormat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SampleFormat", reflect.TypeOf((*MockAudioCodecParameters)(nil).SampleFormat))
}

// SampleRate mocks base method.
func (m *MockAudioCodecParameters) SampleRate() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SampleRate")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// SampleRate indicates an expected call of SampleRate.
func (mr *MockAudioCodecParametersMockRecorder) SampleRate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SampleRate", reflect.TypeOf((*MockAudioCodecParameters)(nil).SampleRate))
}

// SetBitrate mocks base method.
func (m *MockAudioCodecParameters) SetBitrate(arg0 uint) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBitrate", arg0)
}

// SetBitrate indicates an expected call of SetBitrate.
func (mr *MockAudioCodecParametersMockRecorder) SetBitrate(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBitrate", reflect.TypeOf((*MockAudioCodecParameters)(nil).SetBitrate), arg0)
}

// SetStreamIndex mocks base method.
func (m *MockAudioCodecParameters) SetStreamIndex(arg0 uint8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStreamIndex", arg0)
}

// SetStreamIndex indicates an expected call of SetStreamIndex.
func (mr *MockAudioCodecParametersMockRecorder) SetStreamIndex(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStreamIndex", reflect.TypeOf((*MockAudioCodecParameters)(nil).SetStreamIndex), arg0)
}

// StreamIndex mocks base method.
func (m *MockAudioCodecParameters) StreamIndex() uint8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamIndex")
	ret0, _ := ret[0].(uint8)
	return ret0
}

// StreamIndex indicates an expected call of StreamIndex.
func (mr *MockAudioCodecParametersMockRecorder) StreamIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamIndex", reflect.TypeOf((*MockAudioCodecParameters)(nil).StreamIndex))
}

// Tag mocks base method.
func (m *MockAudioCodecParameters) Tag() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tag")
	ret0, _ := ret[0].(string)
	return ret0
}

// Tag indicates an expected call of Tag.
func (mr *MockAudioCodecParametersMockRecorder) Tag() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tag", reflect.TypeOf((*MockAudioCodecParameters)(nil).Tag))
}

// Type mocks base method.
func (m *MockAudioCodecParameters) Type() gomedia.CodecType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(gomedia.CodecType)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockAudioCodecParametersMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockAudioCodecParameters)(nil).Type))
}

// MockPacket is a mock of Packet interface.
type MockPacket struct {
	ctrl     *gomock.Controller
	recorder *MockPacketMockRecorder
	isgomock struct{}
}

// MockPacketMockRecorder is the mock recorder for MockPacket.
type MockPacketMockRecorder struct {
	mock *MockPacket
}

// NewMockPacket creates a new mock instance.
func NewMockPacket(ctrl *gomock.Controller) *MockPacket {
	mock := &MockPacket{ctrl: ctrl}
	mock.recorder = &MockPacketMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPacket) EXPECT() *MockPacketMockRecorder {
	return m.recorder
}

// Clone mocks base method.
func (m *MockPacket) Clone(copyData bool) gomedia.Packet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone", copyData)
	ret0, _ := ret[0].(gomedia.Packet)
	return ret0
}

// Clone indicates an expected call of Clone.
func (mr *MockPacketMockRecorder) Clone(copyData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockPacket)(nil).Clone), copyData)
}

// Data mocks base method.
func (m *MockPacket) Data() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Data")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Data indicates an expected call of Data.
func (mr *MockPacketMockRecorder) Data() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Data", reflect.TypeOf((*MockPacket)(nil).Data))
}

// Duration mocks base method.
func (m *MockPacket) Duration() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Duration")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Duration indicates an expected call of Duration.
func (mr *MockPacketMockRecorder) Duration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Duration", reflect.TypeOf((*MockPacket)(nil).Duration))
}

// Len mocks base method.
func (m *MockPacket) Len() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int)
	return ret0
}

// Len indicates an expected call of Len.
func (mr *MockPacketMockRecorder) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockPacket)(nil).Len))
}

// Release mocks base method.
func (m *MockPacket) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockPacketMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockPacket)(nil).Release))
}

// SetDuration mocks base method.
func (m *MockPacket) SetDuration(arg0 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDuration", arg0)
}

// SetDuration indicates an expected call of SetDuration.
func (mr *MockPacketMockRecorder) SetDuration(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDuration", reflect.TypeOf((*MockPacket)(nil).SetDuration), arg0)
}

// SetSourceID mocks base method.
func (m *MockPacket) SetSourceID(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSourceID", arg0)
}

// SetSourceID indicates an expected call of SetSourceID.
func (mr *MockPacketMockRecorder) SetSourceID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSourceID", reflect.TypeOf((*MockPacket)(nil).SetSourceID), arg0)
}

// SetStartTime mocks base method.
func (m *MockPacket) SetStartTime(arg0 time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStartTime", arg0)
}

// SetStartTime indicates an expected call of SetStartTime.
func (mr *MockPacketMockRecorder) SetStartTime(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStartTime", reflect.TypeOf((*MockPacket)(nil).SetStartTime), arg0)
}

// SetStreamIndex mocks base method.
func (m *MockPacket) SetStreamIndex(arg0 uint8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStreamIndex", arg0)
}

// SetStreamIndex indicates an expected call of SetStreamIndex.
func (mr *MockPacketMockRecorder) SetStreamIndex(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStreamIndex", reflect.TypeOf((*MockPacket)(nil).SetStreamIndex), arg0)
}

// SetTimestamp mocks base method.
func (m *MockPacket) SetTimestamp(arg0 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTimestamp", arg0)
}

// SetTimestamp indicates an expected call of SetTimestamp.
func (mr *MockPacketMockRecorder) SetTimestamp(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTimestamp", reflect.TypeOf((*MockPacket)(nil).SetTimestamp), arg0)
}

// SourceID mocks base method.
func (m *MockPacket) SourceID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SourceID")
	ret0, _ := ret[0].(string)
	return ret0
}

// SourceID indicates an expected call of SourceID.
func (mr *MockPacketMockRecorder) SourceID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SourceID", reflect.TypeOf((*MockPacket)(nil).SourceID))
}

// StartTime mocks base method.
func (m *MockPacket) StartTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// StartTime indicates an expected call of StartTime.
func (mr *MockPacketMockRecorder) StartTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTime", reflect.TypeOf((*MockPacket)(nil).StartTime))
}

// StreamIndex mocks base method.
func (m *MockPacket) StreamIndex() uint8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamIndex")
	ret0, _ := ret[0].(uint8)
	return ret0
}

// StreamIndex indicates an expected call of StreamIndex.
func (mr *MockPacketMockRecorder) StreamIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamIndex", reflect.TypeOf((*MockPacket)(nil).StreamIndex))
}

// Timestamp mocks base method.
func (m *MockPacket) Timestamp() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Timestamp")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Timestamp indicates an expected call of Timestamp.
func (mr *MockPacketMockRecorder) Timestamp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Timestamp", reflect.TypeOf((*MockPacket)(nil).Timestamp))
}

// MockVideoPacket is a mock of VideoPacket interface.
type MockVideoPacket struct {
	ctrl     *gomock.Controller
	recorder *MockVideoPacketMockRecorder
	isgomock struct{}
}

// MockVideoPacketMockRecorder is the mock recorder for MockVideoPacket.
type MockVideoPacketMockRecorder struct {
	mock *MockVideoPacket
}

// NewMockVideoPacket creates a new mock instance.
func NewMockVideoPacket(ctrl *gomock.Controller) *MockVideoPacket {
	mock := &MockVideoPacket{ctrl: ctrl}
	mock.recorder = &MockVideoPacketMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoPacket) EXPECT() *MockVideoPacketMockRecorder {
	return m.recorder
}

// Clone mocks base method.
func (m *MockVideoPacket) Clone(copyData bool) gomedia.Packet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone", copyData)
	ret0, _ := ret[0].(gomedia.Packet)
	return ret0
}

// Clone indicates an expected call of Clone.
func (mr *MockVideoPacketMockRecorder) Clone(copyData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockVideoPacket)(nil).Clone), copyData)
}

// CodecParameters mocks base method.
func (m *MockVideoPacket) CodecParameters() gomedia.VideoCodecParameters {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CodecParameters")
	ret0, _ := ret[0].(gomedia.VideoCodecParameters)
	return ret0
}

// CodecParameters indicates an expected call of CodecParameters.
func (mr *MockVideoPacketMockRecorder) CodecParameters() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CodecParameters", reflect.TypeOf((*MockVideoPacket)(nil).CodecParameters))
}

// Data mocks base method.
func (m *MockVideoPacket) Data() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Data")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Data indicates an expected call of Data.
func (mr *MockVideoPacketMockRecorder) Data() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Data", reflect.TypeOf((*MockVideoPacket)(nil).Data))
}

// Duration mocks base method.
func (m *MockVideoPacket) Duration() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Duration")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Duration indicates an expected call of Duration.
func (mr *MockVideoPacketMockRecorder) Duration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Duration", reflect.TypeOf((*MockVideoPacket)(nil).Duration))
}

// IsKeyFrame mocks base method.
func (m *MockVideoPacket) IsKeyFrame() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsKeyFrame")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsKeyFrame indicates an expected call of IsKeyFrame.
func (mr *MockVideoPacketMockRecorder) IsKeyFrame() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsKeyFrame", reflect.TypeOf((*MockVideoPacket)(nil).IsKeyFrame))
}

// Len mocks base method.
func (m *MockVideoPacket) Len() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int)
	return ret0
}

// Len indicates an expected call of Len.
func (mr *MockVideoPacketMockRecorder) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockVideoPacket)(nil).Len))
}

// Release mocks base method.
func (m *MockVideoPacket) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockVideoPacketMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockVideoPacket)(nil).Release))
}

// SetDuration mocks base method.
func (m *MockVideoPacket) SetDuration(arg0 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDuration", arg0)
}

// SetDuration indicates an expected call of SetDuration.
func (mr *MockVideoPacketMockRecorder) SetDuration(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDuration", reflect.TypeOf((*MockVideoPacket)(nil).SetDuration), arg0)
}

// SetSourceID mocks base method.
func (m *MockVideoPacket) SetSourceID(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSourceID", arg0)
}

// SetSourceID indicates an expected call of SetSourceID.
func (mr *MockVideoPacketMockRecorder) SetSourceID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSourceID", reflect.TypeOf((*MockVideoPacket)(nil).SetSourceID), arg0)
}

// SetStartTime mocks base method.
func (m *MockVideoPacket) SetStartTime(arg0 time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStartTime", arg0)
}

// SetStartTime indicates an expected call of SetStartTime.
func (mr *MockVideoPacketMockRecorder) SetStartTime(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStartTime", reflect.TypeOf((*MockVideoPacket)(nil).SetStartTime), arg0)
}

// SetStreamIndex mocks base method.
func (m *MockVideoPacket) SetStreamIndex(arg0 uint8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStreamIndex", arg0)
}

// SetStreamIndex indicates an expected call of SetStreamIndex.
func (mr *MockVideoPacketMockRecorder) SetStreamIndex(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStreamIndex", reflect.TypeOf((*MockVideoPacket)(nil).SetStreamIndex), arg0)
}

// SetTimestamp mocks base method.
func (m *MockVideoPacket) SetTimestamp(arg0 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTimestamp", arg0)
}

// SetTimestamp indicates an expected call of SetTimestamp.
func (mr *MockVideoPacketMockRecorder) SetTimestamp(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTimestamp", reflect.TypeOf((*MockVideoPacket)(nil).SetTimestamp), arg0)
}

// SourceID mocks base method.
func (m *MockVideoPacket) SourceID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SourceID")
	ret0, _ := ret[0].(string)
	return ret0
}

// SourceID indicates an expected call of SourceID.
func (mr *MockVideoPacketMockRecorder) SourceID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SourceID", reflect.TypeOf((*MockVideoPacket)(nil).SourceID))
}

// StartTime mocks base method.
func (m *MockVideoPacket) StartTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// StartTime indicates an expected call of StartTime.
func (mr *MockVideoPacketMockRecorder) StartTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTime", reflect.TypeOf((*MockVideoPacket)(nil).StartTime))
}

// StreamIndex mocks base method.
func (m *MockVideoPacket) StreamIndex() uint8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamIndex")
	ret0, _ := ret[0].(uint8)
	return ret0
}

// StreamIndex indicates an expected call of StreamIndex.
func (mr *MockVideoPacketMockRecorder) StreamIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamIndex", reflect.TypeOf((*MockVideoPacket)(nil).StreamIndex))
}

// Timestamp mocks base method.
func (m *MockVideoPacket) Timestamp() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Timestamp")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Timestamp indicates an expected call of Timestamp.
func (mr *MockVideoPacketMockRecorder) Timestamp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Timestamp", reflect.TypeOf((*MockVideoPacket)(nil).Timestamp))
}

// MockAudioPacket is a mock of AudioPacket interface.
type MockAudioPacket struct {
	ctrl     *gomock.Controller
	recorder *MockAudioPacketMockRecorder
	isgomock struct{}
}

// MockAudioPacketMockRecorder is the mock recorder for MockAudioPacket.
type MockAudioPacketMockRecorder struct {
	mock *MockAudioPacket
}

// NewMockAudioPacket creates a new mock instance.
func NewMockAudioPacket(ctrl *gomock.Controller) *MockAudioPacket {
	mock := &MockAudioPacket{ctrl: ctrl}
	mock.recorder = &MockAudioPacketMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAudioPacket) EXPECT() *MockAudioPacketMockRecorder {
	return m.recorder
}

// Clone mocks base method.
func (m *MockAudioPacket) Clone(copyData bool) gomedia.Packet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone", copyData)
	ret0, _ := ret[0].(gomedia.Packet)
	return ret0
}

// Clone indicates an expected call of Clone.
func (mr *MockAudioPacketMockRecorder) Clone(copyData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockAudioPacket)(nil).Clone), copyData)
}

// CodecParameters mocks base method.
func (m *MockAudioPacket) CodecParameters() gomedia.AudioCodecParameters {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CodecParameters")
	ret0, _ := ret[0].(gomedia.AudioCodecParameters)
	return ret0
}

// CodecParameters indicates an expected call of CodecParameters.
func (mr *MockAudioPacketMockRecorder) CodecParameters() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CodecParameters", reflect.TypeOf((*MockAudioPacket)(nil).CodecParameters))
}

// Data mocks base method.
func (m *MockAudioPacket) Data() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Data")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Data indicates an expected call of Data.
func (mr *MockAudioPacketMockRecorder) Data() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Data", reflect.TypeOf((*MockAudioPacket)(nil).Data))
}

// Duration mocks base method.
func (m *MockAudioPacket) Duration() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Duration")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Duration indicates an expected call of Duration.
func (mr *MockAudioPacketMockRecorder) Duration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Duration", reflect.TypeOf((*MockAudioPacket)(nil).Duration))
}

// Len mocks base method.
func (m *MockAudioPacket) Len() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int)
	return ret0
}

// Len indicates an expected call of Len.
func (mr *MockAudioPacketMockRecorder) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockAudioPacket)(nil).Len))
}

// Release mocks base method.
func (m *MockAudioPacket) Release() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Release")
}

// Release indicates an expected call of Release.
func (mr *MockAudioPacketMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockAudioPacket)(nil).Release))
}

// SetDuration mocks base method.
func (m *MockAudioPacket) SetDuration(arg0 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDuration", arg0)
}

// SetDuration indicates an expected call of SetDuration.
func (mr *MockAudioPacketMockRecorder) SetDuration(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDuration", reflect.TypeOf((*MockAudioPacket)(nil).SetDuration), arg0)
}

// SetSourceID mocks base method.
func (m *MockAudioPacket) SetSourceID(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSourceID", arg0)
}

// SetSourceID indicates an expected call of SetSourceID.
func (mr *MockAudioPacketMockRecorder) SetSourceID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSourceID", reflect.TypeOf((*MockAudioPacket)(nil).SetSourceID), arg0)
}

// SetStartTime mocks base method.
func (m *MockAudioPacket) SetStartTime(arg0 time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStartTime", arg0)
}

// SetStartTime indicates an expected call of SetStartTime.
func (mr *MockAudioPacketMockRecorder) SetStartTime(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStartTime", reflect.TypeOf((*MockAudioPacket)(nil).SetStartTime), arg0)
}

// SetStreamIndex mocks base method.
func (m *MockAudioPacket) SetStreamIndex(arg0 uint8) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStreamIndex", arg0)
}

// SetStreamIndex indicates an expected call of SetStreamIndex.
func (mr *MockAudioPacketMockRecorder) SetStreamIndex(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStreamIndex", reflect.TypeOf((*MockAudioPacket)(nil).SetStreamIndex), arg0)
}

// SetTimestamp mocks base method.
func (m *MockAudioPacket) SetTimestamp(arg0 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTimestamp", arg0)
}

// SetTimestamp indicates an expected call of SetTimestamp.
func (mr *MockAudioPacketMockRecorder) SetTimestamp(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTimestamp", reflect.TypeOf((*MockAudioPacket)(nil).SetTimestamp), arg0)
}

// SourceID mocks base method.
func (m *MockAudioPacket) SourceID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SourceID")
	ret0, _ := ret[0].(string)
	return ret0
}

// SourceID indicates an expected call of SourceID.
func (mr *MockAudioPacketMockRecorder) SourceID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SourceID", reflect.TypeOf((*MockAudioPacket)(nil).SourceID))
}

// StartTime mocks base method.
func (m *MockAudioPacket) StartTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// StartTime indicates an expected call of StartTime.
func (mr *MockAudioPacketMockRecorder) StartTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartTime", reflect.TypeOf((*MockAudioPacket)(nil).StartTime))
}

// StreamIndex mocks base method.
func (m *MockAudioPacket) StreamIndex() uint8 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamIndex")
	ret0, _ := ret[0].(uint8)
	return ret0
}

// StreamIndex indicates an expected call of StreamIndex.
func (mr *MockAudioPacketMockRecorder) StreamIndex() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamIndex", reflect.TypeOf((*MockAudioPacket)(nil).StreamIndex))
}

// Timestamp mocks base method.
func (m *MockAudioPacket) Timestamp() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Timestamp")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Timestamp indicates an expected call of Timestamp.
func (mr *MockAudioPacketMockRecorder) Timestamp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Timestamp", reflect.TypeOf((*MockAudioPacket)(nil).Timestamp))
}

// MockDemuxer is a mock of Demuxer interface.
type MockDemuxer struct {
	ctrl     *gomock.Controller
	recorder *MockDemuxerMockRecorder
	isgomock struct{}
}

// MockDemuxerMockRecorder is the mock recorder for MockDemuxer.
type MockDemuxerMockRecorder struct {
	mock *MockDemuxer
}

// NewMockDemuxer creates a new mock instance.
func NewMockDemuxer(ctrl *gomock.Controller) *MockDemuxer {
	mock := &MockDemuxer{ctrl: ctrl}
	mock.recorder = &MockDemuxerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDemuxer) EXPECT() *MockDemuxerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDemuxer) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockDemuxerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDemuxer)(nil).Close))
}

// Demux mocks base method.
func (m *MockDemuxer) Demux() (gomedia.CodecParametersPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Demux")
	ret0, _ := ret[0].(gomedia.CodecParametersPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Demux indicates an expected call of Demux.
func (mr *MockDemuxerMockRecorder) Demux() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Demux", reflect.TypeOf((*MockDemuxer)(nil).Demux))
}

// ReadPacket mocks base method.
func (m *MockDemuxer) ReadPacket() (gomedia.Packet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadPacket")
	ret0, _ := ret[0].(gomedia.Packet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadPacket indicates an expected call of ReadPacket.
func (mr *MockDemuxerMockRecorder) ReadPacket() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadPacket", reflect.TypeOf((*MockDemuxer)(nil).ReadPacket))
}

// MockMuxer is a mock of Muxer interface.
type MockMuxer struct {
	ctrl     *gomock.Controller
	recorder *MockMuxerMockRecorder
	isgomock struct{}
}

// MockMuxerMockRecorder is the mock recorder for MockMuxer.
type MockMuxerMockRecorder struct {
	mock *MockMuxer
}

// NewMockMuxer creates a new mock instance.
func NewMockMuxer(ctrl *gomock.Controller) *MockMuxer {
	mock := &MockMuxer{ctrl: ctrl}
	mock.recorder = &MockMuxerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMuxer) EXPECT() *MockMuxerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMuxer) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockMuxerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMuxer)(nil).Close))
}

// Mux mocks base method.
func (m *MockMuxer) Mux(arg0 gomedia.CodecParametersPair) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mux", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mux indicates an expected call of Mux.
func (mr *MockMuxerMockRecorder) Mux(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mux", reflect.TypeOf((*MockMuxer)(nil).Mux), arg0)
}

// WritePacket mocks base method.
func (m *MockMuxer) WritePacket(pkt gomedia.Packet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WritePacket", pkt)
	ret0, _ := ret[0].(error)
	return ret0
}

// WritePacket indicates an expected call of WritePacket.
func (mr *MockMuxerMockRecorder) WritePacket(pkt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WritePacket", reflect.TypeOf((*MockMuxer)(nil).WritePacket), pkt)
}

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// AddURL mocks base method.
func (m *MockReader) AddURL() chan<- string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddURL")
	ret0, _ := ret[0].(chan<- string)
	return ret0
}

// AddURL indicates an expected call of AddURL.
func (mr *MockReaderMockRecorder) AddURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddURL", reflect.TypeOf((*MockReader)(nil).AddURL))
}

// Close mocks base method.
func (m *MockReader) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockReaderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockReader)(nil).Close))
}

// Packets mocks base method.
func (m *MockReader) Packets() <-chan gomedia.Packet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Packets")
	ret0, _ := ret[0].(<-chan gomedia.Packet)
	return ret0
}

// Packets indicates an expected call of Packets.
func (mr *MockReaderMockRecorder) Packets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Packets", reflect.TypeOf((*MockReader)(nil).Packets))
}

// Read mocks base method.
func (m *MockReader) Read() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Read")
}

// Read indicates an expected call of Read.
func (mr *MockReaderMockRecorder) Read() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockReader)(nil).Read))
}

// RemoveURL mocks base method.
func (m *MockReader) RemoveURL() chan<- string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveURL")
	ret0, _ := ret[0].(chan<- string)
	return ret0
}

// RemoveURL indicates an expected call of RemoveURL.
func (mr *MockReaderMockRecorder) RemoveURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveURL", reflect.TypeOf((*MockReader)(nil).RemoveURL))
}

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
	isgomock struct{}
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// AddSource mocks base method.
func (m *MockWriter) AddSource() chan<- string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSource")
	ret0, _ := ret[0].(chan<- string)
	return ret0
}

// AddSource indicates an expected call of AddSource.
func (mr *MockWriterMockRecorder) AddSource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSource", reflect.TypeOf((*MockWriter)(nil).AddSource))
}

// Close mocks base method.
func (m *MockWriter) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockWriterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWriter)(nil).Close))
}

// Done mocks base method.
func (m *MockWriter) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockWriterMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockWriter)(nil).Done))
}

// Packets mocks base method.
func (m *MockWriter) Packets() chan<- gomedia.Packet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Packets")
	ret0, _ := ret[0].(chan<- gomedia.Packet)
	return ret0
}

// Packets indicates an expected call of Packets.
func (mr *MockWriterMockRecorder) Packets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Packets", reflect.TypeOf((*MockWriter)(nil).Packets))
}

// RemoveSource mocks base method.
func (m *MockWriter) RemoveSource() chan<- string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSource")
	ret0, _ := ret[0].(chan<- string)
	return ret0
}

// RemoveSource indicates an expected call of RemoveSource.
func (mr *MockWriterMockRecorder) RemoveSource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSource", reflect.TypeOf((*MockWriter)(nil).RemoveSource))
}

// Write mocks base method.
func (m *MockWriter) Write() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Write")
}

// Write indicates an expected call of Write.
func (mr *MockWriterMockRecorder) Write() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockWriter)(nil).Write))
}

// MockDecoder is a mock of Decoder interface.
type MockDecoder[P gomedia.Packet] struct {
	ctrl     *gomock.Controller
	recorder *MockDecoderMockRecorder[P]
	isgomock struct{}
}

// MockDecoderMockRecorder is the mock recorder for MockDecoder.
type MockDecoderMockRecorder[P gomedia.Packet] struct {
	mock *MockDecoder[P]
}

// NewMockDecoder creates a new mock instance.
func NewMockDecoder[P gomedia.Packet](ctrl *gomock.Controller) *MockDecoder[P] {
	mock := &MockDecoder[P]{ctrl: ctrl}
	mock.recorder = &MockDecoderMockRecorder[P]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDecoder[P]) EXPECT() *MockDecoderMockRecorder[P] {
	return m.recorder
}

// Close mocks base method.
func (m *MockDecoder[P]) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockDecoderMockRecorder[P]) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDecoder[P])(nil).Close))
}

// Decode mocks base method.
func (m *MockDecoder[P]) Decode() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Decode")
}

// Decode indicates an expected call of Decode.
func (mr *MockDecoderMockRecorder[P]) Decode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockDecoder[P])(nil).Decode))
}

// Done mocks base method.
func (m *MockDecoder[P]) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockDecoderMockRecorder[P]) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockDecoder[P])(nil).Done))
}

// Packets mocks base method.
func (m *MockDecoder[P]) Packets() chan<- P {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Packets")
	ret0, _ := ret[0].(chan<- P)
	return ret0
}

// Packets indicates an expected call of Packets.
func (mr *MockDecoderMockRecorder[P]) Packets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Packets", reflect.TypeOf((*MockDecoder[P])(nil).Packets))
}

// MockVideoDecoder is a mock of VideoDecoder interface.
type MockVideoDecoder struct {
	ctrl     *gomock.Controller
	recorder *MockVideoDecoderMockRecorder
	isgomock struct{}
}

// MockVideoDecoderMockRecorder is the mock recorder for MockVideoDecoder.
type MockVideoDecoderMockRecorder struct {
	mock *MockVideoDecoder
}

// NewMockVideoDecoder creates a new mock instance.
func NewMockVideoDecoder(ctrl *gomock.Controller) *MockVideoDecoder {
	mock := &MockVideoDecoder{ctrl: ctrl}
	mock.recorder = &MockVideoDecoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoDecoder) EXPECT() *MockVideoDecoderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockVideoDecoder) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockVideoDecoderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockVideoDecoder)(nil).Close))
}

// Decode mocks base method.
func (m *MockVideoDecoder) Decode() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Decode")
}

// Decode indicates an expected call of Decode.
func (mr *MockVideoDecoderMockRecorder) Decode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockVideoDecoder)(nil).Decode))
}

// Done mocks base method.
func (m *MockVideoDecoder) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockVideoDecoderMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockVideoDecoder)(nil).Done))
}

// FPS mocks base method.
func (m *MockVideoDecoder) FPS() chan<- int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FPS")
	ret0, _ := ret[0].(chan<- int)
	return ret0
}

// FPS indicates an expected call of FPS.
func (mr *MockVideoDecoderMockRecorder) FPS() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FPS", reflect.TypeOf((*MockVideoDecoder)(nil).FPS))
}

// Images mocks base method.
func (m *MockVideoDecoder) Images() <-chan rgb.ReleasableImage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Images")
	ret0, _ := ret[0].(<-chan rgb.ReleasableImage)
	return ret0
}

// Images indicates an expected call of Images.
func (mr *MockVideoDecoderMockRecorder) Images() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Images", reflect.TypeOf((*MockVideoDecoder)(nil).Images))
}

// Packets mocks base method.
func (m *MockVideoDecoder) Packets() chan<- gomedia.VideoPacket {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Packets")
	ret0, _ := ret[0].(chan<- gomedia.VideoPacket)
	return ret0
}

// Packets indicates an expected call of Packets.
func (mr *MockVideoDecoderMockRecorder) Packets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Packets", reflect.TypeOf((*MockVideoDecoder)(nil).Packets))
}

// MockAudioDecoder is a mock of AudioDecoder interface.
type MockAudioDecoder struct {
	ctrl     *gomock.Controller
	recorder *MockAudioDecoderMockRecorder
	isgomock struct{}
}

// MockAudioDecoderMockRecorder is the mock recorder for MockAudioDecoder.
type MockAudioDecoderMockRecorder struct {
	mock *MockAudioDecoder
}

// NewMockAudioDecoder creates a new mock instance.
func NewMockAudioDecoder(ctrl *gomock.Controller) *MockAudioDecoder {
	mock := &MockAudioDecoder{ctrl: ctrl}
	mock.recorder = &MockAudioDecoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAudioDecoder) EXPECT() *MockAudioDecoderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockAudioDecoder) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockAudioDecoderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockAudioDecoder)(nil).Close))
}

// Decode mocks base method.
func (m *MockAudioDecoder) Decode() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Decode")
}

// Decode indicates an expected call of Decode.
func (mr *MockAudioDecoderMockRecorder) Decode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockAudioDecoder)(nil).Decode))
}

// Done mocks base method.
func (m *MockAudioDecoder) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockAudioDecoderMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockAudioDecoder)(nil).Done))
}

// Packets mocks base method.
func (m *MockAudioDecoder) Packets() chan<- gomedia.AudioPacket {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Packets")
	ret0, _ := ret[0].(chan<- gomedia.AudioPacket)
	return ret0
}

// Packets indicates an expected call of Packets.
func (mr *MockAudioDecoderMockRecorder) Packets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Packets", reflect.TypeOf((*MockAudioDecoder)(nil).Packets))
}

// Samples mocks base method.
func (m *MockAudioDecoder) Samples() <-chan gomedia.AudioPacket {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Samples")
	ret0, _ := ret[0].(<-chan gomedia.AudioPacket)
	return ret0
}

// Samples indicates an expected call of Samples.
func (mr *MockAudioDecoderMockRecorder) Samples() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Samples", reflect.TypeOf((*MockAudioDecoder)(nil).Samples))
}

// MockEncoder is a mock of Encoder interface.
type MockEncoder struct {
	ctrl     *gomock.Controller
	recorder *MockEncoderMockRecorder
	isgomock struct{}
}

// MockEncoderMockRecorder is the mock recorder for MockEncoder.
type MockEncoderMockRecorder struct {
	mock *MockEncoder
}

// NewMockEncoder creates a new mock instance.
func NewMockEncoder(ctrl *gomock.Controller) *MockEncoder {
	mock := &MockEncoder{ctrl: ctrl}
	mock.recorder = &MockEncoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncoder) EXPECT() *MockEncoderMockRecorder {
	return m.recorder
}

// Packets mocks base method.
func (m *MockEncoder) Packets() <-chan gomedia.Packet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Packets")
	ret0, _ := ret[0].(<-chan gomedia.Packet)
	return ret0
}

// Packets indicates an expected call of Packets.
func (mr *MockEncoderMockRecorder) Packets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Packets", reflect.TypeOf((*MockEncoder)(nil).Packets))
}

// MockAudioEncoder is a mock of AudioEncoder interface.
type MockAudioEncoder struct {
	ctrl     *gomock.Controller
	recorder *MockAudioEncoderMockRecorder
	isgomock struct{}
}

// MockAudioEncoderMockRecorder is the mock recorder for MockAudioEncoder.
type MockAudioEncoderMockRecorder struct {
	mock *MockAudioEncoder
}

// NewMockAudioEncoder creates a new mock instance.
func NewMockAudioEncoder(ctrl *gomock.Controller) *MockAudioEncoder {
	mock := &MockAudioEncoder{ctrl: ctrl}
	mock.recorder = &MockAudioEncoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAudioEncoder) EXPECT() *MockAudioEncoderMockRecorder {
	return m.recorder
}

// Encode mocks base method.
func (m *MockAudioEncoder) Encode() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Encode")
}

// Encode indicates an expected call of Encode.
func (mr *MockAudioEncoderMockRecorder) Encode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockAudioEncoder)(nil).Encode))
}

// Packets mocks base method.
func (m *MockAudioEncoder) Packets() <-chan gomedia.Packet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Packets")
	ret0, _ := ret[0].(<-chan gomedia.Packet)
	return ret0
}

// Packets indicates an expected call of Packets.
func (mr *MockAudioEncoderMockRecorder) Packets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Packets", reflect.TypeOf((*MockAudioEncoder)(nil).Packets))
}

// Samples mocks base method.
func (m *MockAudioEncoder) Samples() chan<- gomedia.AudioPacket {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Samples")
	ret0, _ := ret[0].(chan<- gomedia.AudioPacket)
	return ret0
}

// Samples indicates an expected call of Samples.
func (mr *MockAudioEncoderMockRecorder) Samples() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Samples", reflect.TypeOf((*MockAudioEncoder)(nil).Samples))
}

// MockHLSMuxer is a mock of HLSMuxer interface.
type MockHLSMuxer struct {
	ctrl     *gomock.Controller
	recorder *MockHLSMuxerMockRecorder
	isgomock struct{}
}

// MockHLSMuxerMockRecorder is the mock recorder for MockHLSMuxer.
type MockHLSMuxerMockRecorder struct {
	mock *MockHLSMuxer
}

// NewMockHLSMuxer creates a new mock instance.
func NewMockHLSMuxer(ctrl *gomock.Controller) *MockHLSMuxer {
	mock := &MockHLSMuxer{ctrl: ctrl}
	mock.recorder = &MockHLSMuxerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHLSMuxer) EXPECT() *MockHLSMuxerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockHLSMuxer) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockHLSMuxerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockHLSMuxer)(nil).Close))
}

// GetFragment mocks base method.
func (m *MockHLSMuxer) GetFragment(ctx context.Context, seg uint64, frag uint8) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFragment", ctx, seg, frag)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFragment indicates an expected call of GetFragment.
func (mr *MockHLSMuxerMockRecorder) GetFragment(ctx, seg, frag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFragment", reflect.TypeOf((*MockHLSMuxer)(nil).GetFragment), ctx, seg, frag)
}

// GetIndexM3u8 mocks base method.
func (m *MockHLSMuxer) GetIndexM3u8(ctx context.Context, msn int64, prt int8) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndexM3u8", ctx, msn, prt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIndexM3u8 indicates an expected call of GetIndexM3u8.
func (mr *MockHLSMuxerMockRecorder) GetIndexM3u8(ctx, msn, prt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndexM3u8", reflect.TypeOf((*MockHLSMuxer)(nil).GetIndexM3u8), ctx, msn, prt)
}

// GetInit mocks base method.
func (m *MockHLSMuxer) GetInit() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInit")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInit indicates an expected call of GetInit.
func (mr *MockHLSMuxerMockRecorder) GetInit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInit", reflect.TypeOf((*MockHLSMuxer)(nil).GetInit))
}

// GetInitByVersion mocks base method.
func (m *MockHLSMuxer) GetInitByVersion(version int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInitByVersion", version)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInitByVersion indicates an expected call of GetInitByVersion.
func (mr *MockHLSMuxerMockRecorder) GetInitByVersion(version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInitByVersion", reflect.TypeOf((*MockHLSMuxer)(nil).GetInitByVersion), version)
}

// GetMasterEntry mocks base method.
func (m *MockHLSMuxer) GetMasterEntry() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMasterEntry")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMasterEntry indicates an expected call of GetMasterEntry.
func (mr *MockHLSMuxerMockRecorder) GetMasterEntry() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMasterEntry", reflect.TypeOf((*MockHLSMuxer)(nil).GetMasterEntry))
}

// GetSegment mocks base method.
func (m *MockHLSMuxer) GetSegment(ctx context.Context, seg uint64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSegment", ctx, seg)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSegment indicates an expected call of GetSegment.
func (mr *MockHLSMuxerMockRecorder) GetSegment(ctx, seg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSegment", reflect.TypeOf((*MockHLSMuxer)(nil).GetSegment), ctx, seg)
}

// Mux mocks base method.
func (m *MockHLSMuxer) Mux(arg0 gomedia.CodecParametersPair) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mux", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mux indicates an expected call of Mux.
func (mr *MockHLSMuxerMockRecorder) Mux(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mux", reflect.TypeOf((*MockHLSMuxer)(nil).Mux), arg0)
}

// UpdateCodecParameters mocks base method.
func (m *MockHLSMuxer) UpdateCodecParameters(arg0 gomedia.CodecParametersPair) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCodecParameters", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCodecParameters indicates an expected call of UpdateCodecParameters.
func (mr *MockHLSMuxerMockRecorder) UpdateCodecParameters(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCodecParameters", reflect.TypeOf((*MockHLSMuxer)(nil).UpdateCodecParameters), arg0)
}

// WritePacket mocks base method.
func (m *MockHLSMuxer) WritePacket(pkt gomedia.Packet) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WritePacket", pkt)
	ret0, _ := ret[0].(error)
	return ret0
}

// WritePacket indicates an expected call of WritePacket.
func (mr *MockHLSMuxerMockRecorder) WritePacket(pkt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WritePacket", reflect.TypeOf((*MockHLSMuxer)(nil).WritePacket), pkt)
}

// MockHLS is a mock of HLS interface.
type MockHLS struct {
	ctrl     *gomock.Controller
	recorder *MockHLSMockRecorder
	isgomock struct{}
}

// MockHLSMockRecorder is the mock recorder for MockHLS.
type MockHLSMockRecorder struct {
	mock *MockHLS
}

// NewMockHLS creates a new mock instance.
func NewMockHLS(ctrl *gomock.Controller) *MockHLS {
	mock := &MockHLS{ctrl: ctrl}
	mock.recorder = &MockHLSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHLS) EXPECT() *MockHLSMockRecorder {
	return m.recorder
}

// GetFragment mocks base method.
func (m *MockHLS) GetFragment(ctx context.Context, uid string, seg uint64, frag uint8) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFragment", ctx, uid, seg, frag)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFragment indicates an expected call of GetFragment.
func (mr *MockHLSMockRecorder) GetFragment(ctx, uid, seg, frag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFragment", reflect.TypeOf((*MockHLS)(nil).GetFragment), ctx, uid, seg, frag)
}

// GetIndexM3u8 mocks base method.
func (m *MockHLS) GetIndexM3u8(ctx context.Context, uid string, msn int64, prt int8) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndexM3u8", ctx, uid, msn, prt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIndexM3u8 indicates an expected call of GetIndexM3u8.
func (mr *MockHLSMockRecorder) GetIndexM3u8(ctx, uid, msn, prt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndexM3u8", reflect.TypeOf((*MockHLS)(nil).GetIndexM3u8), ctx, uid, msn, prt)
}

// GetInit mocks base method.
func (m *MockHLS) GetInit(uid string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInit", uid)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInit indicates an expected call of GetInit.
func (mr *MockHLSMockRecorder) GetInit(uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInit", reflect.TypeOf((*MockHLS)(nil).GetInit), uid)
}

// GetInitByVersion mocks base method.
func (m *MockHLS) GetInitByVersion(uid string, version int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInitByVersion", uid, version)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInitByVersion indicates an expected call of GetInitByVersion.
func (mr *MockHLSMockRecorder) GetInitByVersion(uid, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInitByVersion", reflect.TypeOf((*MockHLS)(nil).GetInitByVersion), uid, version)
}

// GetMasterPlaylist mocks base method.
func (m *MockHLS) GetMasterPlaylist() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMasterPlaylist")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMasterPlaylist indicates an expected call of GetMasterPlaylist.
func (mr *MockHLSMockRecorder) GetMasterPlaylist() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMasterPlaylist", reflect.TypeOf((*MockHLS)(nil).GetMasterPlaylist))
}

// GetSegment mocks base method.
func (m *MockHLS) GetSegment(ctx context.Context, uid string, seg uint64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSegment", ctx, uid, seg)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSegment indicates an expected call of GetSegment.
func (mr *MockHLSMockRecorder) GetSegment(ctx, uid, seg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSegment", reflect.TypeOf((*MockHLS)(nil).GetSegment), ctx, uid, seg)
}

// MockHLSStreamer is a mock of HLSStreamer interface.
type MockHLSStreamer struct {
	ctrl     *gomock.Controller
	recorder *MockHLSStreamerMockRecorder
	isgomock struct{}
}

// MockHLSStreamerMockRecorder is the mock recorder for MockHLSStreamer.
type MockHLSStreamerMockRecorder struct {
	mock *MockHLSStreamer
}

// NewMockHLSStreamer creates a new mock instance.
func NewMockHLSStreamer(ctrl *gomock.Controller) *MockHLSStreamer {
	mock := &MockHLSStreamer{ctrl: ctrl}
	mock.recorder = &MockHLSStreamerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHLSStreamer) EXPECT() *MockHLSStreamerMockRecorder {
	return m.recorder
}

// AddSource mocks base method.
func (m *MockHLSStreamer) AddSource() chan<- string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSource")
	ret0, _ := ret[0].(chan<- string)
	return ret0
}

// AddSource indicates an expected call of AddSource.
func (mr *MockHLSStreamerMockRecorder) AddSource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSource", reflect.TypeOf((*MockHLSStreamer)(nil).AddSource))
}

// Close mocks base method.
func (m *MockHLSStreamer) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockHLSStreamerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockHLSStreamer)(nil).Close))
}

// Done mocks base method.
func (m *MockHLSStreamer) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockHLSStreamerMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockHLSStreamer)(nil).Done))
}

// GetFragment mocks base method.
func (m *MockHLSStreamer) GetFragment(ctx context.Context, uid string, seg uint64, frag uint8) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFragment", ctx, uid, seg, frag)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFragment indicates an expected call of GetFragment.
func (mr *MockHLSStreamerMockRecorder) GetFragment(ctx, uid, seg, frag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFragment", reflect.TypeOf((*MockHLSStreamer)(nil).GetFragment), ctx, uid, seg, frag)
}

// GetIndexM3u8 mocks base method.
func (m *MockHLSStreamer) GetIndexM3u8(ctx context.Context, uid string, msn int64, prt int8) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndexM3u8", ctx, uid, msn, prt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIndexM3u8 indicates an expected call of GetIndexM3u8.
func (mr *MockHLSStreamerMockRecorder) GetIndexM3u8(ctx, uid, msn, prt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndexM3u8", reflect.TypeOf((*MockHLSStreamer)(nil).GetIndexM3u8), ctx, uid, msn, prt)
}

// GetInit mocks base method.
func (m *MockHLSStreamer) GetInit(uid string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInit", uid)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInit indicates an expected call of GetInit.
func (mr *MockHLSStreamerMockRecorder) GetInit(uid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInit", reflect.TypeOf((*MockHLSStreamer)(nil).GetInit), uid)
}

// GetInitByVersion mocks base method.
func (m *MockHLSStreamer) GetInitByVersion(uid string, version int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInitByVersion", uid, version)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInitByVersion indicates an expected call of GetInitByVersion.
func (mr *MockHLSStreamerMockRecorder) GetInitByVersion(uid, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInitByVersion", reflect.TypeOf((*MockHLSStreamer)(nil).GetInitByVersion), uid, version)
}

// GetMasterPlaylist mocks base method.
func (m *MockHLSStreamer) GetMasterPlaylist() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMasterPlaylist")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMasterPlaylist indicates an expected call of GetMasterPlaylist.
func (mr *MockHLSStreamerMockRecorder) GetMasterPlaylist() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMasterPlaylist", reflect.TypeOf((*MockHLSStreamer)(nil).GetMasterPlaylist))
}

// GetSegment mocks base method.
func (m *MockHLSStreamer) GetSegment(ctx context.Context, uid string, seg uint64) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSegment", ctx, uid, seg)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSegment indicates an expected call of GetSegment.
func (mr *MockHLSStreamerMockRecorder) GetSegment(ctx, uid, seg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSegment", reflect.TypeOf((*MockHLSStreamer)(nil).GetSegment), ctx, uid, seg)
}

// Packets mocks base method.
func (m *MockHLSStreamer) Packets() chan<- gomedia.Packet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Packets")
	ret0, _ := ret[0].(chan<- gomedia.Packet)
	return ret0
}

// Packets indicates an expected call of Packets.
func (mr *MockHLSStreamerMockRecorder) Packets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Packets", reflect.TypeOf((*MockHLSStreamer)(nil).Packets))
}

// RemoveSource mocks base method.
func (m *MockHLSStreamer) RemoveSource() chan<- string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSource")
	ret0, _ := ret[0].(chan<- string)
	return ret0
}

// RemoveSource indicates an expected call of RemoveSource.
func (mr *MockHLSStreamerMockRecorder) RemoveSource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSource", reflect.TypeOf((*MockHLSStreamer)(nil).RemoveSource))
}

// Write mocks base method.
func (m *MockHLSStreamer) Write() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Write")
}

// Write indicates an expected call of Write.
func (mr *MockHLSStreamerMockRecorder) Write() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockHLSStreamer)(nil).Write))
}

// MockWebRTC is a mock of WebRTC interface.
type MockWebRTC struct {
	ctrl     *gomock.Controller
	recorder *MockWebRTCMockRecorder
	isgomock struct{}
}

// MockWebRTCMockRecorder is the mock recorder for MockWebRTC.
type MockWebRTCMockRecorder struct {
	mock *MockWebRTC
}

// NewMockWebRTC creates a new mock instance.
func NewMockWebRTC(ctrl *gomock.Controller) *MockWebRTC {
	mock := &MockWebRTC{ctrl: ctrl}
	mock.recorder = &MockWebRTCMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebRTC) EXPECT() *MockWebRTCMockRecorder {
	return m.recorder
}

// Peers mocks base method.
func (m *MockWebRTC) Peers() chan<- *gomedia.WebRTCPeer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Peers")
	ret0, _ := ret[0].(chan<- *gomedia.WebRTCPeer)
	return ret0
}

// Peers indicates an expected call of Peers.
func (mr *MockWebRTCMockRecorder) Peers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Peers", reflect.TypeOf((*MockWebRTC)(nil).Peers))
}

// SortedResolutions mocks base method.
func (m *MockWebRTC) SortedResolutions() *gomedia.WebRTCCodec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SortedResolutions")
	ret0, _ := ret[0].(*gomedia.WebRTCCodec)
	return ret0
}

// SortedResolutions indicates an expected call of SortedResolutions.
func (mr *MockWebRTCMockRecorder) SortedResolutions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SortedResolutions", reflect.TypeOf((*MockWebRTC)(nil).SortedResolutions))
}

// MockWebRTCStreamer is a mock of WebRTCStreamer interface.
type MockWebRTCStreamer struct {
	ctrl     *gomock.Controller
	recorder *MockWebRTCStreamerMockRecorder
	isgomock struct{}
}

// MockWebRTCStreamerMockRecorder is the mock recorder for MockWebRTCStreamer.
type MockWebRTCStreamerMockRecorder struct {
	mock *MockWebRTCStreamer
}

// NewMockWebRTCStreamer creates a new mock instance.
func NewMockWebRTCStreamer(ctrl *gomock.Controller) *MockWebRTCStreamer {
	mock := &MockWebRTCStreamer{ctrl: ctrl}
	mock.recorder = &MockWebRTCStreamerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebRTCStreamer) EXPECT() *MockWebRTCStreamerMockRecorder {
	return m.recorder
}

// AddSource mocks base method.
func (m *MockWebRTCStreamer) AddSource() chan<- string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSource")
	ret0, _ := ret[0].(chan<- string)
	return ret0
}

// AddSource indicates an expected call of AddSource.
func (mr *MockWebRTCStreamerMockRecorder) AddSource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSource", reflect.TypeOf((*MockWebRTCStreamer)(nil).AddSource))
}

// Close mocks base method.
func (m *MockWebRTCStreamer) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockWebRTCStreamerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWebRTCStreamer)(nil).Close))
}

// Done mocks base method.
func (m *MockWebRTCStreamer) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockWebRTCStreamerMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockWebRTCStreamer)(nil).Done))
}

// Packets mocks base method.
func (m *MockWebRTCStreamer) Packets() chan<- gomedia.Packet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Packets")
	ret0, _ := ret[0].(chan<- gomedia.Packet)
	return ret0
}

// Packets indicates an expected call of Packets.
func (mr *MockWebRTCStreamerMockRecorder) Packets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Packets", reflect.TypeOf((*MockWebRTCStreamer)(nil).Packets))
}

// Peers mocks base method.
func (m *MockWebRTCStreamer) Peers() chan<- *gomedia.WebRTCPeer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Peers")
	ret0, _ := ret[0].(chan<- *gomedia.WebRTCPeer)
	return ret0
}

// Peers indicates an expected call of Peers.
func (mr *MockWebRTCStreamerMockRecorder) Peers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Peers", reflect.TypeOf((*MockWebRTCStreamer)(nil).Peers))
}

// RemoveSource mocks base method.
func (m *MockWebRTCStreamer) RemoveSource() chan<- string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSource")
	ret0, _ := ret[0].(chan<- string)
	return ret0
}

// RemoveSource indicates an expected call of RemoveSource.
func (mr *MockWebRTCStreamerMockRecorder) RemoveSource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSource", reflect.TypeOf((*MockWebRTCStreamer)(nil).RemoveSource))
}

// SortedResolutions mocks base method.
func (m *MockWebRTCStreamer) SortedResolutions() *gomedia.WebRTCCodec {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SortedResolutions")
	ret0, _ := ret[0].(*gomedia.WebRTCCodec)
	return ret0
}

// SortedResolutions indicates an expected call of SortedResolutions.
func (mr *MockWebRTCStreamerMockRecorder) SortedResolutions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SortedResolutions", reflect.TypeOf((*MockWebRTCStreamer)(nil).SortedResolutions))
}

// Write mocks base method.
func (m *MockWebRTCStreamer) Write() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Write")
}

// Write indicates an expected call of Write.
func (mr *MockWebRTCStreamerMockRecorder) Write() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockWebRTCStreamer)(nil).Write))
}

// MockSegmenter is a mock of Segmenter interface.
type MockSegmenter struct {
	ctrl     *gomock.Controller
	recorder *MockSegmenterMockRecorder
	isgomock struct{}
}

// MockSegmenterMockRecorder is the mock recorder for MockSegmenter.
type MockSegmenterMockRecorder struct {
	mock *MockSegmenter
}

// NewMockSegmenter creates a new mock instance.
func NewMockSegmenter(ctrl *gomock.Controller) *MockSegmenter {
	mock := &MockSegmenter{ctrl: ctrl}
	mock.recorder = &MockSegmenterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSegmenter) EXPECT() *MockSegmenterMockRecorder {
	return m.recorder
}

// AddSource mocks base method.
func (m *MockSegmenter) AddSource() chan<- string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSource")
	ret0, _ := ret[0].(chan<- string)
	return ret0
}

// AddSource indicates an expected call of AddSource.
func (mr *MockSegmenterMockRecorder) AddSource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSource", reflect.TypeOf((*MockSegmenter)(nil).AddSource))
}

// Close mocks base method.
func (m *MockSegmenter) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockSegmenterMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSegmenter)(nil).Close))
}

// Done mocks base method.
func (m *MockSegmenter) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockSegmenterMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockSegmenter)(nil).Done))
}

// Events mocks base method.
func (m *MockSegmenter) Events() chan<- struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events")
	ret0, _ := ret[0].(chan<- struct{})
	return ret0
}

// Events indicates an expected call of Events.
func (mr *MockSegmenterMockRecorder) Events() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockSegmenter)(nil).Events))
}

// Files mocks base method.
func (m *MockSegmenter) Files() <-chan gomedia.FileInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Files")
	ret0, _ := ret[0].(<-chan gomedia.FileInfo)
	return ret0
}

// Files indicates an expected call of Files.
func (mr *MockSegmenterMockRecorder) Files() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Files", reflect.TypeOf((*MockSegmenter)(nil).Files))
}

// Packets mocks base method.
func (m *MockSegmenter) Packets() chan<- gomedia.Packet {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Packets")
	ret0, _ := ret[0].(chan<- gomedia.Packet)
	return ret0
}

// Packets indicates an expected call of Packets.
func (mr *MockSegmenterMockRecorder) Packets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Packets", reflect.TypeOf((*MockSegmenter)(nil).Packets))
}

// RecordCurStatus mocks base method.
func (m *MockSegmenter) RecordCurStatus() <-chan bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordCurStatus")
	ret0, _ := ret[0].(<-chan bool)
	return ret0
}

// RecordCurStatus indicates an expected call of RecordCurStatus.
func (mr *MockSegmenterMockRecorder) RecordCurStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordCurStatus", reflect.TypeOf((*MockSegmenter)(nil).RecordCurStatus))
}

// RecordMode mocks base method.
func (m *MockSegmenter) RecordMode() chan<- gomedia.RecordMode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordMode")
	ret0, _ := ret[0].(chan<- gomedia.RecordMode)
	return ret0
}

// RecordMode indicates an expected call of RecordMode.
func (mr *MockSegmenterMockRecorder) RecordMode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordMode", reflect.TypeOf((*MockSegmenter)(nil).RecordMode))
}

// RemoveSource mocks base method.
func (m *MockSegmenter) RemoveSource() chan<- string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveSource")
	ret0, _ := ret[0].(chan<- string)
	return ret0
}

// RemoveSource indicates an expected call of RemoveSource.
func (mr *MockSegmenterMockRecorder) RemoveSource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveSource", reflect.TypeOf((*MockSegmenter)(nil).RemoveSource))
}

// Write mocks base method.
func (m *MockSegmenter) Write() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Write")
}

// Write indicates an expected call of Write.
func (mr *MockSegmenterMockRecorder) Write() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockSegmenter)(nil).Write))
}
