// Code generated by MockGen. DO NOT EDIT.
// Source: ffmpeg_screenshoter.go
//
// Generated by this command:
//
//	mockgen -source=ffmpeg_screenshoter.go -destination=../../mocks/mock_screenshoter.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockScreenshoter is a mock of Screenshoter interface.
type MockScreenshoter struct {
	ctrl     *gomock.Controller
	recorder *MockScreenshoterMockRecorder
	isgomock struct{}
}

// MockScreenshoterMockRecorder is the mock recorder for MockScreenshoter.
type MockScreenshoterMockRecorder struct {
	mock *MockScreenshoter
}

// NewMockScreenshoter creates a new mock instance.
func NewMockScreenshoter(ctrl *gomock.Controller) *MockScreenshoter {
	mock := &MockScreenshoter{ctrl: ctrl}
	mock.recorder = &MockScreenshoterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScreenshoter) EXPECT() *MockScreenshoterMockRecorder {
	return m.recorder
}

// Screenshot mocks base method.
func (m *MockScreenshoter) Screenshot(url string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Screenshot", url)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Screenshot indicates an expected call of Screenshot.
func (mr *MockScreenshoterMockRecorder) Screenshot(url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Screenshot", reflect.TypeOf((*MockScreenshoter)(nil).Screenshot), url)
}
