// Code generated by MockGen. DO NOT EDIT.
// Source: mp4io.go
//
// Generated by this command:
//
//	mockgen -source=mp4io.go -destination=../../../mocks/mock_mp4io.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	mp4io "github.com/ugparu/gomedia/format/mp4/mp4io"
	gomock "go.uber.org/mock/gomock"
)

// MockAtom is a mock of Atom interface.
type MockAtom struct {
	ctrl     *gomock.Controller
	recorder *MockAtomMockRecorder
	isgomock struct{}
}

// MockAtomMockRecorder is the mock recorder for MockAtom.
type MockAtomMockRecorder struct {
	mock *MockAtom
}

// NewMockAtom creates a new mock instance.
func NewMockAtom(ctrl *gomock.Controller) *MockAtom {
	mock := &MockAtom{ctrl: ctrl}
	mock.recorder = &MockAtomMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAtom) EXPECT() *MockAtomMockRecorder {
	return m.recorder
}

// Children mocks base method.
func (m *MockAtom) Children() []mp4io.Atom {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Children")
	ret0, _ := ret[0].([]mp4io.Atom)
	return ret0
}

// Children indicates an expected call of Children.
func (mr *MockAtomMockRecorder) Children() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Children", reflect.TypeOf((*MockAtom)(nil).Children))
}

// Len mocks base method.
func (m *MockAtom) Len() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Len")
	ret0, _ := ret[0].(int)
	return ret0
}

// Len indicates an expected call of Len.
func (mr *MockAtomMockRecorder) Len() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Len", reflect.TypeOf((*MockAtom)(nil).Len))
}

// Marshal mocks base method.
func (m *MockAtom) Marshal(arg0 []byte) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Marshal", arg0)
	ret0, _ := ret[0].(int)
	return ret0
}

// Marshal indicates an expected call of Marshal.
func (mr *MockAtomMockRecorder) Marshal(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Marshal", reflect.TypeOf((*MockAtom)(nil).Marshal), arg0)
}

// Pos mocks base method.
func (m *MockAtom) Pos() (int, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pos")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	return ret0, ret1
}

// Pos indicates an expected call of Pos.
func (mr *MockAtomMockRecorder) Pos() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pos", reflect.TypeOf((*MockAtom)(nil).Pos))
}

// Tag mocks base method.
func (m *MockAtom) Tag() mp4io.Tag {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tag")
	ret0, _ := ret[0].(mp4io.Tag)
	return ret0
}

// Tag indicates an expected call of Tag.
func (mr *MockAtomMockRecorder) Tag() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tag", reflect.TypeOf((*MockAtom)(nil).Tag))
}

// Unmarshal mocks base method.
func (m *MockAtom) Unmarshal(arg0 []byte, arg1 int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unmarshal", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unmarshal indicates an expected call of Unmarshal.
func (mr *MockAtomMockRecorder) Unmarshal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unmarshal", reflect.TypeOf((*MockAtom)(nil).Unmarshal), arg0, arg1)
}
