// Code generated by MockGen. DO NOT EDIT.
// Source: audio_encoder.go
//
// Generated by this command:
//
//	mockgen -source=audio_encoder.go -destination=../mocks/mock_audio_encoder.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomedia "github.com/ugparu/gomedia"
	pcm "github.com/ugparu/gomedia/codec/pcm"
	gomock "go.uber.org/mock/gomock"
)

// MockInnerAudioEncoder is a mock of InnerAudioEncoder interface.
type MockInnerAudioEncoder struct {
	ctrl     *gomock.Controller
	recorder *MockInnerAudioEncoderMockRecorder
	isgomock struct{}
}

// MockInnerAudioEncoderMockRecorder is the mock recorder for MockInnerAudioEncoder.
type MockInnerAudioEncoderMockRecorder struct {
	mock *MockInnerAudioEncoder
}

// NewMockInnerAudioEncoder creates a new mock instance.
func NewMockInnerAudioEncoder(ctrl *gomock.Controller) *MockInnerAudioEncoder {
	mock := &MockInnerAudioEncoder{ctrl: ctrl}
	mock.recorder = &MockInnerAudioEncoderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInnerAudioEncoder) EXPECT() *MockInnerAudioEncoderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockInnerAudioEncoder) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockInnerAudioEncoderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockInnerAudioEncoder)(nil).Close))
}

// Encode mocks base method.
func (m *MockInnerAudioEncoder) Encode(pkt *pcm.Packet) ([]gomedia.AudioPacket, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", pkt)
	ret0, _ := ret[0].([]gomedia.AudioPacket)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encode indicates an expected call of Encode.
func (mr *MockInnerAudioEncoderMockRecorder) Encode(pkt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockInnerAudioEncoder)(nil).Encode), pkt)
}

// Init mocks base method.
func (m *MockInnerAudioEncoder) Init(params *pcm.CodecParameters) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Init", params)
	ret0, _ := ret[0].(error)
	return ret0
}

// Init indicates an expected call of Init.
func (mr *MockInnerAudioEncoderMockRecorder) Init(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockInnerAudioEncoder)(nil).Init), params)
}
